### ISSUE TITLE
Erro no Storybook

### ISSUE THREAD

**Issue by mstrcnvs** [helderavila/animavita#1]
https://github.com/helderavila/animavita/blob/037dd065b1a11876f3bbec3526e46319cf67a9b3/src/stories/Card.stories.tsx#L13-L19

Boa noite Helder, tudo bem?

Fui testar o Storybook e acredito que tenha esquecido do parâmetro `otherNames` 👯

**Comment by helderavila** [comment]
Boa noite Rafa, estou ótimo e você?

Sinto muito que obteve esse erro :( , acabei esquecendo de colocar essa prop no Stories do componente 😳.
Acabei de subir um commit para corrigir esse problema e também publiquei ele no link abaixo.
https://6111c9982db2d60039b7314c-mkiuycxymb.chromatic.com/

Obrigado!

**Comment by mstrcnvs** [comment]
Obrigado Helder!
