### ISSUE TITLE
dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by mstrcnvs** [helderavila/animavita#2]
https://github.com/helderavila/animavita/blob/037dd065b1a11876f3bbec3526e46319cf67a9b3/src/components/Card/index.tsx#L46

Boa noite Helder!

Qual foi sua motivação para renderizar a descrição do personagem utilizando a prop `dangerouslySetInnerHTML` e quais são as vulnerabilidades de segurança que isso introduz na aplicação?

Abs.

**Comment by helderavila** [comment]
Olá Rafa!,

Utilizei essa prop pois o conteúdo da descrição em alguns casos contém algumas tag HTML para formatação, mas é necessário tomar muito cuidado ao utilizar essa prop pois se não vier de uma fonte de dados confiável é possível injetar código malicioso no site.

Obrigado!

**Comment by mstrcnvs** [comment]
Obrigado Helder!
