### ISSUE TITLE
Context API

### ISSUE THREAD

**Issue by mstrcnvs** [helderavila/animavita#3]
https://github.com/helderavila/animavita/blob/037dd065b1a11876f3bbec3526e46319cf67a9b3/src/context/CharacterContext.tsx#L32

Boa noite Helder

Quais foram suas motivações para escolher utilizar a Context API neste caso, em vez do Redux, ou de codificar essa lógica de chamada de API diretamente na página?

Abs.

**Comment by helderavila** [comment]
Boa noite Rafa!

Utilizei a Context API pois para aplicações de pequeno porte ela funciona bem, sendo assim utilizar o Redux seria como matar uma formiga com uma bazuka kkkkk. Eu queria expandir a aplicação, colocar mais features e por isso optei por não fazer a chamada api direto nas páginas, acredito que futuramente eu teria que criar um contexto para compartilhar o estado com outros componentes/páginas.

Obrigado!

**Comment by mstrcnvs** [comment]
Obrigado Helder!
