### ISSUE TITLE
Providers

### ISSUE THREAD

**Issue by mstrcnvs** [helderavila/animavita#4]
https://github.com/helderavila/animavita/blob/037dd065b1a11876f3bbec3526e46319cf67a9b3/src/App.tsx#L12-L15

Boa noite Helder

Qual seria sua sugestão para manter o código claro e conciso na medida que o número de providers fosse crescendo, com a introdução de novos tipos de operações, dados, e APIs?

Abs.

**Comment by helderavila** [comment]
Boa noite Rafa!

Uma alternativa para isso é passar o provider somente nos components/páginas que realmente estão utilizando daquele estado, assim o app.tsx já ficaria mais limpo e também seria mais performatico pois não iria fazer a renderização novamente de componentes que não utilizam daquele estado, também é possivel abstrair os providers em uma função. 

Obrigado!

**Comment by mstrcnvs** [comment]
Obrigado Helder!
